@extends('layouts.app', ['class' => 'bg-gris-oxford'])

@section('content')
@include('layouts.headers.guest')

<div class="container mt--5 pb-5">
    <!-- Table -->
    <div class="row">
        <div class="col-12">
            <div class="card shadow border-0 p-5" style="color: #2d2d2d">
                <center><h2 class="text-rosita">TÉRMINOS Y CONDICIONES DE PARTY SERVICE.</h2></center>
                <p></p>
                <p class="text-justify">Bienvenido a Party Service, D. Power S. de R.L de C.V le ofrecen funciones de sitio web y aplicación móvil cuando visita o compra en Party Service, utiliza los productos o servicios de Party Service, usa las aplicaciones de Party Service para dispositivos móviles o emplea software puesto a disposición por Party Service en relación con lo anterior. Party Service le presta los Servicios de Party Service bajo las siguientes condiciones.</p>
                <p class="text-justify"><b>Al utilizar los Servicios de Party Service, usted acepta estas condiciones. Le rogamos que las lea detenidamente.</b> Ofrecemos una amplia gama de Servicios en Party Service, y en ocasiones pueden aplicarse condiciones adicionales. Cada vez que utilice cualquier Servicio de Party Service (por ejemplo, Tu Perfil o aplicaciones de Party Service para móvil) usted estará igualmente sujeto a los lineamientos, términos y condiciones particulares aplicables a dicho Servicio de Party Service (las "Condiciones Generales de los Servicios"). Las Condiciones Generales de los Servicios, prevalecerán sobre las Condiciones de Uso en caso de discrepancia de ambas.</p>
                <h3 class="text-rosita">COMUNICACIONES ELECTRÓNICAS</h3>
                <p class="text-justify">Cada vez que utilice un Servicio de Party Service o nos envíe un correo electrónico, mensaje de texto y otras comunicaciones de cualquier dispositivo, estará comunicándose electrónicamente con nosotros. Usted acepta recibir comunicaciones de nosotros electrónicamente en una variedad de formas, por ejemplo, mediante los siguientes tipos de mensajes de datos: correo electrónico, mensajes de texto, notificaciones automáticas de nuestra app o mediante avisos y mensajes colocados en este sitio web o mediante los demás Servicios de Party Service, como nuestro Centro de Mensajes. Usted acepta que todos los contratos, avisos, mensajes, y otras notificaciones y comunicaciones que le enviemos por medios electrónicos satisfacen cualquier requisito legal de forma escrita y cuentan con plenos efectos legales y validez.</p>
                <h3 class="text-rosita">DERECHOS DE AUTOR</h3>
                <p class="text-justify">Todo contenido alojado o puesto a disposición a través de cualquiera de los Servicios de Party Service, como por ejemplo texto, gráficos, logotipos, iconos de botones, imágenes, clips de audio, descargas digitales, y recopilaciones de datos son propiedad de Party Service o de sus proveedores de contenido y está protegido por las leyes internacionales y de los Estados Unidos Mexicanos de propiedad intelectual. El conjunto de todo el contenido albergado o puesto a disposición a través de cualquier Servicio de Party Service es propiedad exclusiva de Party Service, y está protegido por las leyes internacionales y de los Estados Unidos Mexicanos de propiedad intelectual.</p>
                <h3 class="text-rosita">LICENCIA Y ACCESO</h3>
                <p class="text-justify">Sujeto al cumplimiento por parte de usted de estas Condiciones de Uso y las Condiciones Generales de los Servicios aplicables, así como al pago del precio aplicable, en su caso, Party Service o sus proveedores de contenidos le conceden una licencia limitada no exclusiva, no transferible y no sub-licenciable, de acceso y utilización, a los Servicios de Party Service para fines personales no comerciales. Esta licencia no incluye derecho alguno de reventa ni de uso comercial de ninguno de los Servicios de Party Service ni de sus contenidos; derecho alguno a compilar ni utilizar lista alguna de productos, descripciones o precios; derecho alguno a realizar ningún uso derivado de los Servicios de Party Service ni de sus contenidos; a descargar o copiar información de cuenta alguna para el beneficio de otra empresa; ni el uso de herramientas o robots de búsqueda y extracción de datos o similar.<br><br> Party Service y sus licenciantes, proveedores, editores, titulares de derechos u otros proveedores de contenidos se reservan cualquier derecho que no esté expresamente comprendido en estas Condiciones de Uso o en las Condiciones Generales de los Servicios. No está permitida la reproducción, duplicación, copia, venta, reventa o explotación de ningún tipo de los Servicios de Party Service ni de parte alguna de los mismos con fines comerciales, en cada caso sin nuestro previo consentimiento por escrito.<br><br> Tampoco está permitido colocar o utilizar técnicas de colocación para introducir cualquier marca comercial, logotipo u otra información protegida por derechos de autor (incluyendo imágenes, texto, diseños de página o formatos) de Party Service sin el consentimiento correspondiente previo por escrito. No está permitido el uso de metaetiquetas (meta tags) ni de ningún otro "texto oculto" que utilice los nombres o marcas de Party Service sin nuestro consentimiento previo y por escrito. No podrá usted hacer un uso incorrecto de los Servicios de Party Service. Sólo le está permitido utilizar los Servicios de Party Service de forma lícita. Cualquier incumplimiento por usted de estas Condiciones de Uso o de las Condiciones Generales de los Servicios supondrá la terminación de las licencias otorgadas por Party Service.</p>
                <h3 class="text-rosita">SU CUENTA</h3>
                <p class="text-justify">Es posible que usted requiera crear una cuenta de Party Service propia, acceder a la misma y contar con un método de pago válido asociado a su cuenta para utilizar ciertos Servicios de Party Service. En caso de que surja un problema con su método de pago seleccionado, podríamos realizar el cargo a cualquier otro método de pago válido asociado a su cuenta.  Cuando usted utiliza los Servicios de Party Service es usted responsable de mantener la confidencialidad de los datos de su cuenta y su contraseña, así como de restringir el acceso a su computadora y demás dispositivos, y usted asume la responsabilidad de cualesquier actividades realizadas desde su cuenta o utilizando su contraseña.</p>
                <p class="text-justify">Party Service comercializa productos para menores de edad, pero los vende a mayores de edad, quienes pueden adquirirlos con una tarjeta de crédito u otro método de pago autorizado. Si es usted menor de 18 años de edad, puede usted utilizar los Servicios de Party Service únicamente con la participación e involucramiento de uno de sus padres o tutores. Debes ser mayor de 18 años para comprar bebidas alcohólicas o para navegar los listados relacionados con ellas.</p>
                <p class="text-justify">Party Service se reserva el derecho de dar de baja cuentas, remover o editar contenido, cancelar ordenes en caso de violación a las presentes Condiciones de Uso, Condiciones Generales de los Servicios o cualquier política, términos y condiciones de Party Service, derechos de terceros o comisión de un delito o cualquier conducta que dañe la reputación de Party Service.</p>
                <h3 class="text-rosita">RIESGO DE PÉRDIDA</h3>
                <p class="text-justify">Todos los productos comprados en Party Service se llevan a cabo a través de un contrato de embarque. La propiedad y el riesgo de pérdida de los productos le será transferida a usted en el momento en que entreguemos los productos al transportista correspondiente. Usted consiente expresamente en que le cobremos su compra ya sea al momento en que le son enviados.</p>
                <p class="text-justify">Party Service no asume la titularidad del producto devuelto hasta la recepción del mismo en la dirección de devolución. Nos reservamos el derecho, a nuestra discreción, a reembolsar el importe del producto sin exigir su devolución. En tal caso, la titularidad del producto cuyo precio hubiera sido reembolsado no pasará a Party Service</p>
                <h3 class="text-rosita">RIESGO DE PÉRDIDA</h3>
                <p class="text-justify">Toda la información acerca de los productos contenida en nuestro sitio web y aplicación móvil se proporciona únicamente con fines informativos. Antes de usar los productos siempre lea las etiquetas, advertencias e instrucciones de uso de los productos. Party Service intenta ser tan preciso como sea posible. Sin embargo, Party Service no garantiza que las descripciones o el contenido de cualquier otro Servicio de Party Service sea preciso, completo, confiable, vigente o libre de errores. Si usted considera que un producto ofrecido en Party Service no cumple con su descripción, el único recurso del que usted dispone será devolverlo, siempre y cuando sea devuelto sin haberse utilizado y conforme a los Términos y Condiciones.</p>
                <h3 class="text-rosita">PRECIOS</h3>
                <p class="text-justify">Excepto que se indiquen de manera separada, todos los precios mostrados a través de los Servicios de Party Service incluyen impuestos.</p>
                <p class="text-justify">Salvo en la medida en que se indique lo contrario, el Precio de Lista o Precio Sugerido que aparece para productos en cualquier Servicio de Party Service representa el precio de venta al público listado en dicho producto, sugerido por el fabricante o proveedor, o estimado de conformidad con prácticas estándar de la industria; o el precio estimado de venta al público respecto de un producto comparable ofrecido en otro lugar. </p>
                <p class="text-justify">El Precio de Lista o Precio Sugerido es un estimado de precio comparativo y puede o no representar el precio vigente en todos los lugares en una fecha determinada. Cuando el producto sea ofrecido para venta por alguno de nuestros comerciantes, el Precio de Lista o Precio Sugerido podrá ser proporcionado por el comerciante.</p>

            </div>
        </div>
    </div>    

@endsection